[package]
name = "vega-xfce"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
homepage.workspace = true
description = "Interface GTK4 do centro de controle Vega para XFCE"

[[bin]]
name = "vega-xfce"
path = "src/main.rs"

[dependencies]
gtk = { package = "gtk4", version = "0.11.4", features = ["v4_10"] }
adw = { package = "libadwaita", version = "0.9.2", features = ["v1_5"] }
base64 = "0.22.1"
reqwest = { version = "0.12.24", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
roxmltree = "0.21.1"
futures-util = "0.3.32"
lyra-vega-dbus = { git = "https://github.com/lyra-os-linux/lyra-vega-dbus", tag = "v5.1.22" }
