[workspace]
resolver = "3"
members = ["vega-xfce"]

[workspace.package]
version = "5.1.30"
edition = "2024"
license = "GPL-3.0"
authors = ["Rodrigo Brito"]
rust-version = "1.92"
homepage = "https://github.com/lyra-os-linux/vega-xfce"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"
