mod assistant;
mod backup;
mod bluetooth;
mod datetime;
mod dock;
mod kernel;
mod logs;
mod menu;
mod monitor;
mod network;
mod screen;
mod screensaver;
mod services;
mod shell;
mod snapshots;
mod software;
mod sparkline;
mod storage;
mod users;
mod wallpaper;

pub use assistant::AssistantPage;
pub use backup::BackupPage;
pub use bluetooth::BluetoothPage;
pub use datetime::DateTimePage;
pub use dock::DockPage;
pub use kernel::KernelPage;
pub use logs::LogsPage;
pub use menu::MenuPage;
pub use monitor::{MonitorPage, Rates};
pub use network::NetworkPage;
pub use screen::ScreenPage;
pub use screensaver::ScreensaverPage;
pub use services::ServicesPage;
pub use shell::VegaShell;
pub use snapshots::SnapshotsPage;
pub use software::SoftwarePage;
pub use storage::StoragePage;
pub use users::UsersPage;
pub use wallpaper::WallpaperPage;
